hmcts/draft-store

build.gradle, src/main/java/uk/gov/hmcts/reform/draftstore/config/DraftStoreConfig.java
Upgrade logging library to latest version (currently at bintray)
```
[ ] Yes
[x] No
```
=> Upgrade logging library

src/functionalTest/java/uk/gov/hmcts/reform/draftstore/data/DataAgent.java, src/functionalTest/java/uk/gov/hmcts/reform/draftstore/endpoint/AbstractDraftStoreEndpointTest.java, src/main/java/uk/gov/hmcts/reform/draftstore/data/DraftStoreDAO.java, src/main/java/uk/gov/hmcts/reform/draftstore/endpoint/EndpointExceptionHandler.java, src/main/java/uk/gov/hmcts/reform/draftstore/endpoint/v1/DraftStoreEndpoint.java, src/main/java/uk/gov/hmcts/reform/draftstore/endpoint/v2/DraftStoreEndpoint.java, src/main/java/uk/gov/hmcts/reform/draftstore/service/JsonConstraintValidator.java, src/main/java/uk/gov/hmcts/reform/draftstore/service/UserIdentificationService.java, src/main/java/uk/gov/hmcts/reform/draftstore/service/ValidJson.java
Fixed all checkstyle issues. Mainly wildcard imports and too long lines.
```
[ ] Yes
[x] No
```
=> Fix checkstyle issues

src/main/java/uk/gov/hmcts/reform/draftstore/data/DraftStoreDAO.java
Cleaning up a bit.
```
[ ] Yes
[x] No
```
=> Clean up DAO

src/main/java/uk/gov/hmcts/reform/draftstore/endpoint/EndpointExceptionHandler.java, src/main/java/uk/gov/hmcts/reform/draftstore/endpoint/domain/ErrorResult.java
Removing for simplicity, this model has only 2 fields.
Also fixed some formatting. I will address other formatting inconsistencies (across the project) on a separate pull request.
```
[ ] Yes
[x] No
```
=> Remove ErrorResult builder

src/functionalTest/java/uk/gov/hmcts/reform/draftstore/data/DataAgent.java, src/functionalTest/java/uk/gov/hmcts/reform/draftstore/data/DraftStoreDAOTest.java, src/functionalTest/java/uk/gov/hmcts/reform/draftstore/endpoint/AbstractDraftStoreEndpointTest.java, src/functionalTest/java/uk/gov/hmcts/reform/draftstore/endpoint/HandleUnknownExceptionTest.java, src/functionalTest/java/uk/gov/hmcts/reform/draftstore/endpoint/v2/DraftStoreEndpointTest.java, src/main/java/uk/gov/hmcts/reform/draftstore/endpoint/EndpointExceptionHandler.java, src/main/java/uk/gov/hmcts/reform/draftstore/endpoint/domain/ErrorCode.java
Consistent formatting.
```
[ ] Yes
[x] No
```
=> Fix code formatting

src/functionalTest/java/uk/gov/hmcts/reform/draftstore/endpoint/v3/Create.java, src/functionalTest/java/uk/gov/hmcts/reform/draftstore/endpoint/v3/CreateTest.java, src/functionalTest/java/uk/gov/hmcts/reform/draftstore/endpoint/v3/GetAllTest.java, src/functionalTest/java/uk/gov/hmcts/reform/draftstore/endpoint/v3/GetByIdTest.java, src/main/java/uk/gov/hmcts/reform/draftstore/data/DraftStoreDAO.java, src/main/java/uk/gov/hmcts/reform/draftstore/domain/CreateDraft.java, src/main/java/uk/gov/hmcts/reform/draftstore/endpoint/v3/DraftController.java, src/main/java/uk/gov/hmcts/reform/draftstore/service/validation/JsonObject.java, src/main/java/uk/gov/hmcts/reform/draftstore/service/validation/JsonObjectValidator.java
In line with new API
```
[ ] Yes
[x] No
```
=> new create draft endpoint

src/functionalTest/java/uk/gov/hmcts/reform/draftstore/endpoint/v3/UpdateTest.java, src/main/java/uk/gov/hmcts/reform/draftstore/data/DraftStoreDAO.java, src/main/java/uk/gov/hmcts/reform/draftstore/domain/UpdateDraft.java, src/main/java/uk/gov/hmcts/reform/draftstore/endpoint/v3/DraftController.java, src/main/java/uk/gov/hmcts/reform/draftstore/exception/AuthorizationException.java
New endpoint for updating by its ID
```
[ ] Yes
[x] No
```
=> Add new update endpoint

src/functionalTest/java/uk/gov/hmcts/reform/draftstore/endpoint/v3/DeleteTest.java, src/main/java/uk/gov/hmcts/reform/draftstore/data/DraftStoreDAO.java, src/main/java/uk/gov/hmcts/reform/draftstore/endpoint/v3/DraftController.java
=> Add new delete endpoint

src/main/resources/application.yaml
now available at http://localhost:8800/swagger-ui.html
```
[ ] Yes
[x] No
```
=> Fix swagger ui

src/functionalTest/java/uk/gov/hmcts/reform/draftstore/endpoint/v3/CreateTest.java, src/main/java/uk/gov/hmcts/reform/draftstore/data/DraftStoreDAO.java, src/main/java/uk/gov/hmcts/reform/draftstore/endpoint/v3/DraftController.java
=> Add missing `Location` header to 'create' response

src/main/resources/application.yaml
=> Set default empty value for idam url

src/functionalTest/java/uk/gov/hmcts/reform/draftstore/data/DataAgent.java, src/functionalTest/java/uk/gov/hmcts/reform/draftstore/endpoint/v3/DeleteTest.java, src/functionalTest/java/uk/gov/hmcts/reform/draftstore/endpoint/v3/GetByIdTest.java, src/functionalTest/java/uk/gov/hmcts/reform/draftstore/endpoint/v3/UpdateTest.java, src/functionalTest/java/uk/gov/hmcts/reform/draftstore/endpoint/v3/helpers/SampleData.java, src/main/java/uk/gov/hmcts/reform/draftstore/config/DraftStoreConfig.java, src/main/java/uk/gov/hmcts/reform/draftstore/data/DraftStoreDAO.java, src/main/java/uk/gov/hmcts/reform/draftstore/domain/Draft.java, src/main/resources/db/migration/V5__add_created_and_updated_columns.sql
Store information on when draft has be created and last updated.
Using https://en.wikipedia.org/wiki/ISO_8601 format.
```
[ ] Yes
[x] No
```
=> Add `created` and `updated` fields

src/functionalTest/java/uk/gov/hmcts/reform/draftstore/data/OldDraftsCleanupTest.java, src/functionalTest/java/uk/gov/hmcts/reform/draftstore/endpoint/v3/helpers/SampleData.java, src/main/java/uk/gov/hmcts/reform/draftstore/DraftStoreApplication.java, src/main/java/uk/gov/hmcts/reform/draftstore/config/DraftStoreConfig.java, src/main/java/uk/gov/hmcts/reform/draftstore/data/DraftStoreDAO.java, src/main/java/uk/gov/hmcts/reform/draftstore/domain/CreateDraft.java, src/main/java/uk/gov/hmcts/reform/draftstore/service/ScheduledTasks.java, src/main/resources/application.yaml, src/main/resources/db/migration/V6__add_max_age_column.sql, src/main/resources/db/migration/V6__add_max_stale_days_column.sql
Drafts created via old api (v2) do not get removed.
```
[ ] Yes
[x] No
```
=> Add max stale time, remove old drafts periodically

build.gradle, ruleset.xml
This is part of quality assurance activity to standardise the code. Few simple rules (basic, braces, unnecessary and unusedcode) should be enough for a good start.
```
[ ] Yes
[x] No
```
=> Enable PMD gradle plugin

src/functionalTest/java/uk/gov/hmcts/reform/draftstore/endpoint/v3/CreateTest.java, src/functionalTest/java/uk/gov/hmcts/reform/draftstore/endpoint/v3/DeleteTest.java, src/functionalTest/java/uk/gov/hmcts/reform/draftstore/endpoint/v3/GetAllTest.java, src/functionalTest/java/uk/gov/hmcts/reform/draftstore/endpoint/v3/GetByIdTest.java, src/functionalTest/java/uk/gov/hmcts/reform/draftstore/endpoint/v3/UpdateTest.java, src/main/java/uk/gov/hmcts/reform/draftstore/endpoint/v3/DraftController.java, src/main/java/uk/gov/hmcts/reform/draftstore/service/AuthService.java, src/main/java/uk/gov/hmcts/reform/draftstore/service/UserAndService.java
Simplify code a bit in preparation for using Spring Security and async calls to IDAM and S2S.
No
=> Refactor auth

build.gradle
There's some test dependencies that would be good to update but they would likely require some code changes
=> Update compile deps

src/functionalTest/java/uk/gov/hmcts/reform/draftstore/data/PaginationTest.java, src/functionalTest/java/uk/gov/hmcts/reform/draftstore/endpoint/HandleUnknownExceptionTest.java, src/functionalTest/java/uk/gov/hmcts/reform/draftstore/endpoint/v3/GetAllTest.java, src/main/java/uk/gov/hmcts/reform/draftstore/data/DraftStoreDAO.java, src/main/java/uk/gov/hmcts/reform/draftstore/domain/DraftList.java, src/main/java/uk/gov/hmcts/reform/draftstore/endpoint/v3/DraftController.java, src/main/java/uk/gov/hmcts/reform/draftstore/utils/Lists.java
Adding pagination, as required by https://hmcts.github.io/restful-api-standards/#pagination
```
[x] Yes
[ ] No
```
=> Add pagination

src/functionalTest/java/uk/gov/hmcts/reform/draftstore/endpoint/v3/CreateTest.java, src/functionalTest/java/uk/gov/hmcts/reform/draftstore/endpoint/v3/DeleteTest.java, src/functionalTest/java/uk/gov/hmcts/reform/draftstore/endpoint/v3/GetAllTest.java, src/functionalTest/java/uk/gov/hmcts/reform/draftstore/endpoint/v3/GetByIdTest.java, src/functionalTest/java/uk/gov/hmcts/reform/draftstore/endpoint/v3/UpdateTest.java, src/main/java/uk/gov/hmcts/reform/draftstore/endpoint/v3/DraftController.java, src/main/java/uk/gov/hmcts/reform/draftstore/service/DraftService.java, src/test/java/uk/gov/hmcts/reform/draftstore/service/draftservice/BaseTest.java, src/test/java/uk/gov/hmcts/reform/draftstore/service/draftservice/DeleteTest.java, src/test/java/uk/gov/hmcts/reform/draftstore/service/draftservice/ReadManyTest.java, src/test/java/uk/gov/hmcts/reform/draftstore/service/draftservice/ReadSingleTest.java, src/test/java/uk/gov/hmcts/reform/draftstore/service/draftservice/UpdateTest.java
Mostly in preparation for encryption (which will be added to `DraftService`)
```
[ ] Yes
[x] No
```
=> Refactor - add service layer

src/main/java/uk/gov/hmcts/reform/draftstore/service/crypto/CryptoService.java, src/main/java/uk/gov/hmcts/reform/draftstore/service/crypto/GeneralSecurityRuntimeException.java, src/main/java/uk/gov/hmcts/reform/draftstore/service/crypto/Length.java, src/main/java/uk/gov/hmcts/reform/draftstore/utils/IllegalArgument.java, src/main/resources/db/migration/V8__add_encrypted_doc_column.sql, src/test/java/uk/gov/hmcts/reform/draftstore/service/crypto/CryptoServiceTest.java
Just the service with tests. Not used by API yet.
```
[ ] Yes
[x] No
```
=> add crypto service

src/main/java/uk/gov/hmcts/reform/draftstore/domain/Draft.java, src/main/java/uk/gov/hmcts/reform/draftstore/service/mappers/FromDbModelMapper.java
=> Remove no longer needed fields from api model

README.md
Grade + coverage
```
[ ] Yes
[x] No
```
=> Add Codacy badges

src/functionalTest/java/uk/gov/hmcts/reform/draftstore/endpoint/v3/CreateTest.java, src/functionalTest/java/uk/gov/hmcts/reform/draftstore/endpoint/v3/UpdateTest.java, src/main/java/uk/gov/hmcts/reform/draftstore/endpoint/v3/DraftController.java
*Does this PR introduce a breaking change?** (check one with "x")
```
[ ] Yes
[x] No
```
=> Remove duplicated constant

src/gatling/resources/conf/application.conf, src/gatling/scala/uk/gov/hmcts/reform/draftstore/CreateMultipleDrafts.scala, src/gatling/scala/uk/gov/hmcts/reform/draftstore/actions/Create.scala, src/gatling/scala/uk/gov/hmcts/reform/draftstore/actions/ReadOne.scala, src/gatling/scala/uk/gov/hmcts/reform/draftstore/actions/setup/Idam.scala
Create a new account in Idam and sign in to retrieve token later passed to draft-store.
=> Use idam in gatling tests

src/main/java/uk/gov/hmcts/reform/draftstore/service/idam/IdamClientStub.java, src/main/java/uk/gov/hmcts/reform/draftstore/service/s2s/S2sClientStub.java
... as `userID` column in db is `varchar(256)`
```
[ ] Yes
[x] No
```
=> Support real tokens in idam client stub

src/gatling/resources/conf/application.conf, src/gatling/scala/uk/gov/hmcts/reform/draftstore/actions/setup/LeaseServiceToken.scala
=> Make gatling config file more consistent

src/gatling/scala/uk/gov/hmcts/reform/draftstore/CreateMultipleDrafts.scala, src/gatling/scala/uk/gov/hmcts/reform/draftstore/utils/IdamTokensHolder.scala
Create all accounts and sign in to IDAM before starting any requests to draft-store.
=> Create users in a separate gatling scenario

src/gatling/scala/uk/gov/hmcts/reform/draftstore/actions/Create.scala, src/gatling/scala/uk/gov/hmcts/reform/draftstore/actions/ReadOne.scala
Best viewed without whitespace changes:
https://github.com/hmcts/draft-store/pull/62/files?w=1
```
[ ] Yes
[x] No
```
=> Encrypt drafts in gatling tests

build.gradle
=> Remove not used testing dependencies

ruleset.xml, src/main/java/uk/gov/hmcts/reform/draftstore/service/DraftService.java, src/test/java/uk/gov/hmcts/reform/draftstore/service/crypto/CryptoServiceTest.java
added new pmd rule, fixed issues.
=> Clean up imports

publish-swagger-docs.sh
=> Don't publish empty swagger doc

src/functionalTest/java/uk/gov/hmcts/reform/draftstore/data/DraftStoreDAOTest.java, src/functionalTest/java/uk/gov/hmcts/reform/draftstore/endpoint/v3/DeleteAllTest.java, src/main/java/uk/gov/hmcts/reform/draftstore/data/DraftStoreDAO.java, src/main/java/uk/gov/hmcts/reform/draftstore/endpoint/v3/DraftController.java, src/main/java/uk/gov/hmcts/reform/draftstore/service/DraftService.java
=> Add route for deleting all user's drafts

src/gatling/scala/uk/gov/hmcts/reform/draftstore/CreateMultipleDrafts.scala, src/gatling/scala/uk/gov/hmcts/reform/draftstore/actions/DeleteAll.scala
=> Clean up drafts after gatling test

build.gradle
>Spring Boot 1.5.8 includes [over 40 fixes, improvements and dependency updates](https://github.com/spring-projects/spring-boot/milestone/91?closed=1)
=> Upgrade spring boot to 1.5.8

build.gradle, src/main/java/uk/gov/hmcts/reform/draftstore/config/DraftStoreConfig.java
Does this PR introduce a breaking change?** (check one with "x")
```
[ ] Yes
[x] No
```
=> Remove no longer needed dependency

doc/arch/adr-001-only-128-bit-encryption.md
We should be recording the key architectural decisions being made as we
build our services.
I've used the format described by Michael Nygard here: http://thinkrelevance.com/blog/2011/11/15/documenting-architecture-decisions
```
[ ] Yes
[x] No
```
=> Add an architecture decision register to the repo

README.md
It's a legal requirement that we make it clear to operators of this
service that they must _not_ breach privacy and view the persisted data,
through any means.
```
[ ] Yes
[x] No
```
=> Add GDPR note requested by Data and Security Architecture

doc/db-schema.md
Spells out to less technical audiences what the db schema is
```
[ ] Yes
[x] No
```
=> Add database schema documentation

build.gradle
https://tools.hmcts.net/jira/browse/ROC-1105
Use latest java-logging to make use of updated request tracing features.
```
[ ] Yes
[X] No
```
=> Update java-logging version

src/main/java/uk/gov/hmcts/reform/draftstore/data/DraftStoreDAO.java
By the date it was last updated. Latest on top.
=> Sort unencrypted drafts info

doc/arch/adr-001-only-128-bit-encryption.md
@rkondratowicz at #92 
```
[X] Yes
[ ] No
```
=> [ci skip] Fixed "encrpytion" typo

Jenkinsfile_CNP
https://tools.hmcts.net/jira/browse/RPE-343
```
[ ] Yes
[x] No
```
=> Run integration tests within Jenkins pipeline

infrastructure/main.tf
Fix infrastructure code for postgres DB. Current version is outdates and doesn't work.
```
[ ] Yes
[x] No
```
=> Fix infrastructure code for postgres DB

.travis.yml, README.md
use codecov instead of codacy for test coverage
=> Switch to codecov

infrastructure/main.tf, infrastructure/variables.tf
Provide webapp module with subscription parameter (which is required)
```
[ ] Yes
[x] No
```
=> Provide webapp module with subscription parameter

Jenkinsfile_parameterised
Add Jenkinsfile_parameterised so that the product can be deployed to Sandbox.
```
[ ] Yes
[x] No
```
=> Add Jenkinsfile_parameterised

Jenkinsfile_parameterized
Fix the syntax in Jenkinsfile_parameterized
```
[ ] Yes
[x] No
```
=> Fix the syntax in Jenkinsfile_parameterized

infrastructure/state.tf
Fix the config in state.tf
```
[ ] Yes
[x] No
```
=> Fix the config in state.tf

infrastructure/main.tf, infrastructure/variables.tf
Let Jenkins set component name in terraform (otherwise the deployment would fail).
```
[ ] Yes
[x] No
```
=> Let Jenkins set component name in terraform

build.gradle, web.config
Remove version from jar name and save standard output to files
```
[ ] Yes
[x] No
```
=> Remove version from jar name and save standard output to files

Jenkinsfile, build.gradle
Remove the -all suffix from jar name
```
[ ] Yes
[x] No
```
=> Remove the -all suffix from jar name

build.gradle, infrastructure/main.tf, infrastructure/output.tf, infrastructure/variables.tf, src/integrationTest/java/uk/gov/hmcts/reform/draftstore/data/migration/DisableFlywayMigrationStrategy.java, src/main/java/uk/gov/hmcts/reform/draftstore/config/FlywayConfiguration.java, src/main/java/uk/gov/hmcts/reform/draftstore/data/migration/FlywayNoOpStrategy.java, src/main/java/uk/gov/hmcts/reform/draftstore/exception/PendingMigrationScriptException.java, src/main/resources/application.yaml, src/test/java/uk/gov/hmcts/reform/draftstore/data/migration/FlywayNoOpStrategyTest.java
https://tools.hmcts.net/jira/browse/RPE-377
https://tools.hmcts.net/jira/browse/RPE-344
Enable db migrations in pipeline. Also, fix the way the application talks to the DB (with current settings it can't).
```
[ ] Yes
[x] No
```
=> Enable db migrations in pipeline

Jenkinsfile_CNP
https://tools.hmcts.net/jira/browse/RPE-377
Add slack notifications and DB migrations to main pipeline
```
[ ] Yes
[x] No
```
=> Add slack notifications and DB migrations to main pipeline

infrastructure/demo.tfvars, infrastructure/main.tf, infrastructure/prod.tfvars, infrastructure/variables.tf
Make the app talk to the right instances of Idam and s2s
```
[ ] Yes
[x] No
```
=> Make the app talk to the right instances of Idam and s2s

infrastructure/aat.tfvars
Map aat to tactical preprod (Idam is still in tactical)
```
[ ] Yes
[x] No
```
=> Map aat to tactical preprod

Jenkinsfile_CNP, Jenkinsfile_parameterized, infrastructure/aat.tfvars, infrastructure/demo.tfvars, infrastructure/main.tf, infrastructure/output.tf, infrastructure/prod.tfvars, infrastructure/test_config.tf, infrastructure/variables.tf
https://tools.hmcts.net/jira/browse/RPE-341
https://tools.hmcts.net/jira/browse/RPE-342
Provide the necessary infrastructure setup for smoke and functional tests.
```
[ ] Yes
[x] No
```
=> Provide the infrastructure setup for end-to-end tests

infrastructure/output.tf
https://tools.hmcts.net/jira/browse/RPE-341
Add test Idam user email to end-to-end test configuration
```
[ ] Yes
[x] No
```
=> Add Idam test user email to smoke test config

infrastructure/variables.tf
Remove the port from test Idam URL (shouldn't be there)
```
[ ] Yes
[x] No
```
=> Remove the port from test Idam URL

Jenkinsfile
Update the command for dependency check in Jenkinsfile (changed to dependencyCheckAnalyze)
```
[ ] Yes
[x] No
```
=> Update the command for dependency check in Jenkinsfile

build.gradle, src/smokeTest/java/uk/gov/hmcts/reform/draftstore/ApplicationSmokeTest.java, src/smokeTest/java/uk/gov/hmcts/reform/draftstore/SmokeTestSuite.java, src/smokeTest/java/uk/gov/hmcts/reform/draftstore/client/IdamClient.java, src/smokeTest/java/uk/gov/hmcts/reform/draftstore/client/S2sClient.java, src/smokeTest/resources/application.properties
https://tools.hmcts.net/jira/browse/RPE-341
Create smoke test suite with all the common test setup
```
[ ] Yes
[x] No
```
=> Create smoke test suite

src/smokeTest/java/uk/gov/hmcts/reform/draftstore/ApplicationSmokeTest.java, src/smokeTest/java/uk/gov/hmcts/reform/draftstore/SmokeTestSuite.java, src/smokeTest/java/uk/gov/hmcts/reform/draftstore/client/DraftStoreClient.java, src/smokeTest/java/uk/gov/hmcts/reform/draftstore/response/Draft.java, src/smokeTest/java/uk/gov/hmcts/reform/draftstore/response/DraftList.java
https://tools.hmcts.net/jira/browse/RPE-341
Add smoke tests for the service
```
[ ] Yes
[x] No
```
=> Add smoke tests for the service

src/smokeTest/java/uk/gov/hmcts/reform/draftstore/SmokeTestSuite.java
Add a missing closing bracket in configuration property binding
```
[ ] Yes
[x] No
```
=> Add a missing closing bracket in configuration property binding

infrastructure/main.tf, infrastructure/variables.tf
Move the database location from West Europe to UK South.
```
[ ] Yes
[x] No
```
=> Move the database location from West Europe to UK South

infrastructure/variables.tf
=> Switch back to tactical

infrastructure/aat.tfvars, infrastructure/main.tf, infrastructure/prod.tfvars, infrastructure/variables.tf
https://tools.hmcts.net/confluence/display/CNP/Preview+Environment#PreviewEnvironment-Reducecapacity
=> Use only one azure node by default

infrastructure/variables.tf
=> Point to sidam on sandbox aat

infrastructure/main.tf, infrastructure/variables.tf
[Confluence page](https://tools.hmcts.net/confluence/display/CNP/Preview+Environment#PreviewEnvironment-TerraformConfiguration)
=> Add `common_tags` to terraform files

infrastructure/saat.tfvars
Added saat.tfvars and changed IDAM url pointing to tactical Test 
```
[ ] Yes
[ X] No
```
=> Changing IDAM URL to point back to tactical from strategic

infrastructure/saat.tfvars, infrastructure/sandbox.tfvars, infrastructure/sprod.tfvars, infrastructure/variables.tf
**NOT TO BE MERGED UNTIL CONFIRMED**
Point saat draft store to saat idam. Also, remove the default value for IDAM URL.
```
[ ] Yes
[x] No
```
=> Point saat draft store to saat idam

infrastructure/saat.tfvars
activate testing support, need to look at how we use testing support on sidam, because apparently it doesn't work
```
[ ] Yes
[ ] No
```
=> Activate testing support

infrastructure/aat.tfvars
Needed for retest of performance of pipeline today
```
[ ] Yes
[ ] No
```
=> Switch to SIDAM

infrastructure/aat.tfvars
=> Back to TIDAM

infrastructure/main.tf, infrastructure/variables.tf
https://tools.hmcts.net/jira/browse/RPE-544
Get DB password from Azure Key Vault instead of tactical vault.
```
[ ] Yes
[x] No
```
=> [PREVIEW] Move DB password from tactical vault to Azure Key Vault

dependency-check-suppressions.xml
Postgres. Same as other repos.
=> Add dependency check suppression

infrastructure/aat.tfvars, infrastructure/prod.tfvars
Planned and approved SIDAM production testing for CMC
=> sidam dry-run

infrastructure/alert_bad_response_code.tf
https://tools.hmcts.net/jira/browse/RPE-916
It matches what we have in production
Tested in SAAT
```
[ ] Yes
[ ] No
```
=> RPE-916 Automate alerts

src/integrationTest/java/uk/gov/hmcts/reform/draftstore/controllers/internal/HttpStatusControllerTest.java, src/main/java/uk/gov/hmcts/reform/draftstore/controllers/internal/HttpStatusController.java, src/main/java/uk/gov/hmcts/reform/draftstore/controllers/internal/HttpStatusResponse.java
https://tools.hmcts.net/jira/browse/RPE-916
This will allow triggering the new alert to make sure its working, will discuss with the team whether its useful to keep around after or if it should be removed
```
[ ] Yes
[ ] No
```
=> RPE-916 Add debug endpoint for triggering alert

infrastructure/alert_bad_response_code.tf
https://tools.hmcts.net/jira/browse/RPE-916
Pass in the resource group of the action group: downstream of: https://github.com/hmcts/cnp-module-metric-alert/pull/4
```
[ ] Yes
[ ] No
```
=> RPE-916 Fix action group association

src/main/resources/application.yaml
=> fixed the config for management endpoint

Dockerfile
https://tools.hmcts.net/jira/browse/RPE-922
Testing new docker image with new jdk options. See:
https://www.oracle.com/technetwork/java/javase/8u191-relnotes-5032181.html#JDK-8146115
```
[ ] Yes
[x] No
```
=> Update image to alpine 3.9 jre 1.8-191

Dockerfile
Remove unused env var from Docker file
```
[ ] Yes
[x] No
```
=> Remove unneeded env var

infrastructure/main.tf
https://tools.hmcts.net/jira/browse/RPE-345
Use PAAS database instead of IAAS
```
[ ] Yes
[ ] No
```
=> RPE-345 Use PAAS database in the application

build.gradle, charts/draft-store-service/requirements.yaml, docker-compose.yml
https://tools.hmcts.net/jira/browse/RPE-879
Moving to latest chart and java logging versions
```
[ ] Yes
[x] No
```
=> Upgraded to latest logging n chart

src/test/java/uk/gov/hmcts/reform/draftstore/controllers/ReportControllerTest.java
https://tools.hmcts.net/jira/browse/ROC-5323
Deployment of new reports endpoint failed for test coverage. Adding tests for new code.
```
[ ] Yes
[x] No
```
=> ROC-5323 Add tests for report controller

charts/draft-store-service/Chart.yaml, charts/draft-store-service/requirements.yaml, charts/draft-store-service/values.template.yaml
Adding tag to postgres to be able to control in AAT
https://tools.hmcts.net/jira/browse/RPE-985
Adding tag to postgres to be able to control in AAT
```
[ ] Yes
[x] No
```
=> Adding tag to postgres to be able to control in AAT

build.gradle, charts/draft-store-service/Chart.yaml, charts/draft-store-service/requirements.yaml, charts/draft-store-service/values.template.yaml, src/main/resources/bootstrap.yaml
Added password as secret
https://tools.hmcts.net/jira/browse/RPE-985
Added password as secret
```
[ ] Yes
[x] No
```
=> Added password as secret

build.gradle
Fixing dependency issue
NA
Fixing dependency issue
```
[ ] Yes
[x] No
```
=> Fixing dependency issue

Jenkinsfile_CNP, charts/draft-store-service/values.aat.template.yaml
Code freeze for SIDAM so making necessary changes for PR pipelines.
```
[ ] Yes
[x] No
```
=> Add SIDAM changes

infrastructure/main.tf
Added common_tags  to key vault tf to fix build.
NA
Added common_tags  to key vault tf to fix build.
```
[ ] Yes
[x] No
```
=> Added common_tags  to key vault

infrastructure/main.tf
Upgrade TF provider
NA
Upgrade TF provider
```
[ ] Yes
[x] No
```
=> Upgrade TF provider

Jenkinsfile_CNP, charts/draft-store-service/Chart.yaml, charts/draft-store-service/requirements.yaml, charts/draft-store-service/values.aat.template.yaml, charts/draft-store-service/values.preview.template.yaml, charts/draft-store-service/values.yaml, config/owasp/suppressions.xml, infrastructure/main.tf
Refactor AKS environment configuration in Preview
https://tools.hmcts.net/jira/browse/RPE-914
Refactor AKS environment configuration in Preview
```
[ ] Yes
[x] No
```
=>  RPE-914 Refactor AKS environment configuration in Preview

Jenkinsfile_nightly, build.gradle, src/gatling/conf/application.conf, src/gatling/conf/logback.xml, src/gatling/simulations/uk/gov/hmcts/reform/draftstore/CreateMultipleDrafts.scala, src/gatling/simulations/uk/gov/hmcts/reform/draftstore/actions/Create.scala, src/gatling/simulations/uk/gov/hmcts/reform/draftstore/actions/DeleteAll.scala, src/gatling/simulations/uk/gov/hmcts/reform/draftstore/actions/ReadAll.scala, src/gatling/simulations/uk/gov/hmcts/reform/draftstore/actions/ReadOne.scala, src/gatling/simulations/uk/gov/hmcts/reform/draftstore/actions/Update.scala, src/gatling/simulations/uk/gov/hmcts/reform/draftstore/actions/setup/Idam.scala, src/gatling/simulations/uk/gov/hmcts/reform/draftstore/actions/setup/LeaseServiceToken.scala, src/gatling/simulations/uk/gov/hmcts/reform/draftstore/utils/IdamUserHolder.scala
https://tools.hmcts.net/jira/browse/RPE-409
Add performance tests and enable in nightly pipeline
```
[ ] Yes
[x] No
```
=> Add performance tests and enable in nightly pipeline

Jenkinsfile_CNP, charts/draft-store-service/values.aat.template.yaml
https://tools.hmcts.net/jira/browse/RPE-1045
Enabling deployment to AAT staging
```
[ ] Yes
[x] No
```
=> Enabling deployment to AAT staging

infrastructure/main.tf, infrastructure/state.tf
To fix: 
```
Error: Error running plan: 1 error(s) occurred:
* local.ase_name: local.ase_name: Resource 'data.terraform_remote_state.core_apps_compute' does not have attribute 'ase_name' for variable 'data.terraform_remote_state.core_apps_compute.ase_name'
```
```
[ ] Yes
[x] No
```
=> Drop remote state reference

build.gradle
https://github.com/rest-assured/rest-assured/issues/1168#issuecomment-493355009
```
[ ] Yes
[ ] No
```
=> Use ext for version for rest assured

charts/draft-store-service/Chart.yaml, charts/draft-store-service/requirements.yaml
https://dev.azure.com/hmcts/Platform%20Engineering/_workitems/edit/109
Bump java chart version
```
[ ] Yes
[x] No
```
[AB#109](https://dev.azure.com/hmcts/90472b63-dc8d-4ae6-8819-a32bd211e914/_workitems/edit/109)
=> bump java chart version

infrastructure/main.tf, infrastructure/sandbox.tfvars, infrastructure/variables.tf
Fixes [AB#122](https://dev.azure.com/hmcts/90472b63-dc8d-4ae6-8819-a32bd211e914/_workitems/edit/122)
Add access policy for managed identity in sandbox
```
[ ] Yes
[ ] No
```
=> Add access policy for draft store sandbox

Jenkinsfile_CNP, build.gradle, config/owasp/suppressions.xml
Test for [[AB#202](https://dev.azure.com/hmcts/90472b63-dc8d-4ae6-8819-a32bd211e914/_workitems/edit/202)]
```
[ ] Yes
[x] No
```
=> Update owasp dependency check to version 5

Dockerfile
[[AB#244](https://dev.azure.com/hmcts/90472b63-dc8d-4ae6-8819-a32bd211e914/_workitems/edit/244)]
Base images have been migrated to hmcts public where they are automatically patched and scanned.
```
[ ] Yes
[x] No
```
=> Migrate to hmctspublic registry

Dockerfile
[[AB#244](https://dev.azure.com/hmcts/90472b63-dc8d-4ae6-8819-a32bd211e914/_workitems/edit/244)]
```
[ ] Yes
[x] No
```
=> Migrate to new repo conventions

Jenkinsfile_CNP, charts/draft-store-service/Chart.yaml
=> Test prod registry change

charts/draft-store-service/requirements.yaml, charts/draft-store-service/values.yaml
[AB#94](https://dev.azure.com/hmcts/90472b63-dc8d-4ae6-8819-a32bd211e914/_workitems/edit/94)
Swap registry
```
[ ] Yes
[ ] No
```
=> Use hmctspublic chart

charts/draft-store-service/values.aat.template.yaml, infrastructure/aat.tfvars
Fixes [AB#385](https://dev.azure.com/hmcts/90472b63-dc8d-4ae6-8819-a32bd211e914/_workitems/edit/385)
```
[ ] Yes
[x] No
```
=> Adding Pod Identity in AAT

.dependabot/config.yml, Jenkinsfile_CNP, build.gradle
=> Update jackson databind

infrastructure/perftest.tfvars
=> managed identiy for perftest AKS

build.gradle
=> Upgrade jackson databind

build.gradle, charts/draft-store-service/requirements.yaml, docker-compose.yml, src/main/resources/application.yaml
-
Expose prometheus metrics
```
[ ] Yes
[ ] No
```
=> Add prometheus metrics

charts/draft-store-service/Chart.yaml, charts/draft-store-service/requirements.yaml
=> Bumping java chart

Jenkinsfile_CNP, Jenkinsfile_parameterized
=> Merge to ithc

build.gradle, config/checkstyle/checkstyle.xml
=> Fix owasp dep check failure, bumping checkstyle

build.gradle
=> fixing owasp failure

Jenkinsfile_CNP, Jenkinsfile_parameterized, build.gradle, config/checkstyle/checkstyle.xml, infrastructure/.gitignore, infrastructure/aat.tfvars, infrastructure/alert_bad_response_code.tf, infrastructure/demo.tfvars, infrastructure/ithc.tfvars, infrastructure/main.tf, infrastructure/output.tf, infrastructure/perftest.tfvars, infrastructure/prod.tfvars, infrastructure/sandbox.tfvars, infrastructure/variables.tf
=> merge master to ithc

charts/draft-store-service/Chart.yaml, charts/draft-store-service/values.aat.template.yaml, charts/draft-store-service/values.preview.template.yaml, charts/draft-store-service/values.yaml
Pros:
Reduces the need to override ingress, env variables, keyvaults in each environment in flux.
Cons: 
Not readily runnable in local / demo and needs change in env variables. 
```
[ ] Yes
[x] No
```
=> Making env variables dynamic to reduce variables overriden in each env

Jenkinsfile_CNP, infrastructure/aat.tfvars
=> cleanup ase in aat

infrastructure/prod.tfvars
=> cleanup prod

infrastructure/ithc.tfvars, infrastructure/perftest.tfvars
=> cleanup ithc perftest

config/owasp/suppressions.xml
=> fix owasp issue

build.gradle
=> Revert "Bump org.flywaydb.flyway from 5.2.4 to 6.0.2"

charts/draft-store-service/Chart.yaml, charts/draft-store-service/requirements.yaml, config/owasp/suppressions.xml
=> Bumping to latest java chart

charts/draft-store-service/Chart.yaml, charts/draft-store-service/requirements.yaml
=> Use latest chart java

charts/draft-store-service/Chart.yaml, charts/draft-store-service/values.yaml
=> Fix image in published chart

build.gradle, infrastructure/perftest.tfvars
=> Fix perftest objectId

build.gradle, charts/draft-store-service/Chart.yaml, charts/draft-store-service/requirements.yaml, charts/draft-store-service/values.aat.template.yaml, charts/draft-store-service/values.preview.template.yaml, charts/draft-store-service/values.yaml, config/owasp/suppressions.xml, infrastructure/main.tf
=> Adding appinsights to keyvault and bumping chart

charts/draft-store-service/Chart.yaml, charts/draft-store-service/values.yaml, src/main/resources/bootstrap.yaml
=> Adding appinsights key as secret to chart

Dockerfile, build.gradle, config/owasp/suppressions.xml, web.config
Failing dependency check.
```
[ ] Yes
[x] No
```
=> Upgrade applicationinsights jars

src/main/resources/bootstrap.yaml
Currently appinsights seems to be not working
```
[ ] Yes
[x] No
```
=> fixing app insights

src/main/resources/application.yaml
=> Use datasource default settings

Jenkinsfile_CNP
=> Switch back to jenkins library master branch

src/main/resources/application.yaml
[AB#504](https://dev.azure.com/hmcts/90472b63-dc8d-4ae6-8819-a32bd211e914/_workitems/edit/504)
See docs here:
https://grafana.com/grafana/dashboards/4701
```
[ ] Yes
[ ] No
```
=> Tag metrics with app name for prometheus

Jenkinsfile_CNP, charts/draft-store-service/Chart.yaml, charts/draft-store-service/values.preview.template.yaml
=> Helm-2.16.1 changes

Jenkinsfile_CNP
[[AB#641](https://dev.azure.com/hmcts/90472b63-dc8d-4ae6-8819-a32bd211e914/_workitems/edit/641)]
```
[ ] Yes
[x] No
```
=> In-container tests fixes

Jenkinsfile_CNP
[[AB#720](https://dev.azure.com/hmcts/90472b63-dc8d-4ae6-8819-a32bd211e914/_workitems/edit/720)]
```
[ ] Yes
[x] No
```
=> Test slack notification for build fix

Jenkinsfile_CNP, charts/draft-store-service/requirements.yaml
[[AB#720](https://dev.azure.com/hmcts/90472b63-dc8d-4ae6-8819-a32bd211e914/_workitems/edit/720)]
```
[ ] Yes
[x] No
```
=> Use state configmap when running in-cluster tests

charts/draft-store-service/Chart.yaml
=> Bump chart version (missed from previous commit)

Jenkinsfile_parameterized
=> Fix deprecation in parameterized build

charts/draft-store-service/Chart.yaml, charts/draft-store-service/requirements.yaml
=> Upgrade to latest chart-java

Jenkinsfile_CNP
[AB#892]
```
[ ] Yes
[x] No
```
=> Test (empty) PR for external-dns

charts/draft-store-service/Chart.yaml, charts/draft-store-service/requirements.yaml
=> Upgrade to latest chart java

Jenkinsfile_CNP, build.gradle, config/owasp/suppressions.xml
=> Upgrade dependencies.

build.gradle, config/owasp/suppressions.xml
=> Update dependencies. Clean up suppressions

.gitignore, charts/draft-store-service/Chart.yaml
=> Bump base chart

.github/renovate.json, renovate.json
=> Add renovate for helm requirements

charts/draft-store-service/Chart.yaml
=> Remove tilde from requirements

infrastructure/main.tf
=> Add shared MI

infrastructure/aat.tfvars, infrastructure/demo.tfvars, infrastructure/ithc.tfvars, infrastructure/main.tf, infrastructure/perftest.tfvars, infrastructure/prod.tfvars, infrastructure/sandbox.tfvars, infrastructure/variables.tf
=> Remove old MI

Jenkinsfile_CNP
[AB#901]
```
[ ] Yes
[ ] No
```
=> Build using jenkins docker agent

Jenkinsfile_CNP
[AB#901]
```
[ ] Yes
[x] No
```
=> Revert to Jenkins master branch

Jenkinsfile_CNP, Jenkinsfile_nightly
=> Test jenkins pipeline

Jenkinsfile_CNP, Jenkinsfile_nightly
=> Revert to master branch pipeline

Jenkinsfile_CNP
[AB#1032]
```
[ ] Yes
[x] No
```
=> Test docker inbound-agent build process

Jenkinsfile_CNP
[AB#1032]
```
[x] Yes
[ ] No
```
=> Revert docker agent test change

Jenkinsfile_CNP, README.md
=> Fix branch

Jenkinsfile_parameterized
=> Remove installCharts from parameterized build

src/main/java/uk/gov/hmcts/reform/draftstore/data/DraftStoreDao.java
=> Fix quality gate error

src/main/java/uk/gov/hmcts/reform/draftstore/data/DraftStoreDao.java
=> Fix quality gate error (as sonar likes?)

src/main/java/uk/gov/hmcts/reform/draftstore/data/DraftStoreDao.java
=> Fix quality gate error (sonar driven syntax)

infrastructure/state.tf, infrastructure/versions.tf
[[AB#1070](https://dev.azure.com/hmcts/90472b63-dc8d-4ae6-8819-a32bd211e914/_workitems/edit/1070)]
```
[ ] Yes
[ ] No
```
=> Fixes for terraform provider upgrade

infrastructure/main.tf
=> Fix appinsights tf application_type

infrastructure/variables.tf
=> Fix testing_support var type

Jenkinsfile_CNP
=> Test parallel image + test image build

Jenkinsfile_CNP
=> Revert test parallel docker image build

Jenkinsfile_CNP
For testing Jenkins library pr to uninstall staging HRs after tests have completed.
```
[ ] Yes
[x ] No
```
=> to test uninstall of staging hr after testing

Jenkinsfile_CNP
=> revert infra branch to master

.github/renovate.json
=> test terraform manager

infrastructure/state.tf
=> Remove wild card to test renovate

infrastructure/main.tf
Adding postgress v11 database in preparation for migration.
```
[ ] Yes
[x] No
```
=> Add v11 postgresDB

Jenkinsfile_CNP, build.gradle, config/owasp/suppressions.xml, src/contractTest/java/uk/gov/hmcts/reform/draftstore/controllers/DivorceDraftControllerProviderTest.java, src/contractTest/java/uk/gov/hmcts/reform/draftstore/controllers/DraftControllerProviderTestConfiguration.java, src/contractTest/resources/application.yml
=> TA-83: Initial code for Provider test for Divorce

infrastructure/main.tf
https://github.com/hmcts/cnp-jenkins-config/pull/586
https://github.com/hmcts/cnp-module-postgres/pull/51
Plan to merge postgres PR later today but want a green e2e on path to live, making sure permissions are setup properly etc
=> Test permissions are in place for aad-auth postgres

infrastructure/main.tf
=> Revert "Test permissions are in place for aad-auth postgres"

infrastructure/main.tf
=> Move to master cnp-module-keyvault

infrastructure/main.tf
https://tools.hmcts.net/jira/browse/DTSPO-264
Separates out the product var so it can be used for read access in production
```
[ ] Yes
[ ] No
```
=> DTSPO-264 Set name for postgres DB

infrastructure/main.tf
Support ticket open with microsoft, not working via SP
=> Revert "DTSPO-264 Set name for postgres DB"

Jenkinsfile_CNP, build.gradle, src/contractTest/java/uk/gov/hmcts/reform/draftstore/controllers/DivorceDraftControllerProviderTest.java
=> TA-451: Point tag to master and ignore no pacts to verify

infrastructure/main.tf
https://tools.hmcts.net/jira/browse/DTSPO-563
Draftstore database upgrade to v11 - sandbox
```
[ ] Yes
[x ] No
```
=> draftstore upgrade to PostgreSQL v11 - Sandbox changes

charts/draft-store-service/Chart.yaml
=> upgrading to 3.4.9 chart-java

Jenkinsfile_CNP, build.gradle
=> move to jitpack

charts/draft-store-service/Chart.yaml
=> Bump chart-java version

Dockerfile, acb.tpl.yaml
https://tools.hmcts.net/jira/browse/DTSPO-5983
Added multi-architecture ACR Task template.
```
[ ] Yes
[X] No
```
=> Added multi-architecture ACR Task template.

build.gradle, charts/draft-store-service/Chart.yaml, config/owasp/suppressions.xml
=> Upgrade java chart and dependencies

charts/draft-store-service/Chart.yaml, charts/draft-store-service/values.preview.template.yaml
=> Upgrading java chart

.github/renovate.json
=> Add regex manager

Jenkinsfile_CNP, Jenkinsfile_parameterized, infrastructure/.gitignore, infrastructure/alert_bad_response_code.tf
https://tools.hmcts.net/jira/browse/DTSPO-11969
Add expiresAfter tag to resources in sbox
Updates to metric alert module will cause the existing template resource to be deleted and recreated due to switching from a deprecated resource to a new version
```
[ ] Yes
[x] No
```
=> DTSPO-11969 - Add expiresAfter in sbox

Jenkinsfile_CNP, Jenkinsfile_parameterized
https://tools.hmcts.net/jira/browse/DTSPO-11969
Remove expires in sbox since it's not needed in this repo
```
[ ] Yes
[x] No
```
=> DTSPO-11969 - Remove expiresAfter in sbox

config/owasp/suppressions.xml
Suppressing as it looks like a false positive and there's no fixes in the latest version either
https://github.com/jeremylong/DependencyCheck/issues/5502
```
[ ] Yes
[x] No
```
=> Suppress CVE-2022-45688 looks like a false positive

infrastructure/main.tf
Added vnet provider to use correct vnet and so the postgres-vnet-provider branch can be merged into master
```
[ ] Yes
[x] No
```
=> DTSPO-13423 - add vnet provider

infrastructure/main.tf
[DTSPO-13248](https://tools.hmcts.net/jira/browse/DTSPO-13248)
updating flex server resource group
```
[ ] Yes
[x] No
```
=> DTSPO-13248 Updating flex server rg

infrastructure/main.tf
Removing single server as migration is now complete.
```
[ ] Yes
[x] No
```
=> DTSPO-13832 - remove single server

charts/draft-store-service/Chart.yaml, charts/draft-store-service/values.yaml
https://tools.hmcts.net/jira/browse/DTSPO-13832
Update values to use flexible server
Pipeline currently fails due to it attempting to connect to, now deleted, single server
```
[ ] Yes
[x] No
```
=> DTSPO-13832 - Update db values to flexible server

infrastructure/alert_bad_response_code.tf, infrastructure/main.tf, infrastructure/variables.tf
https://tools.hmcts.net/jira/browse/DTSPO-13832
Fixing error related to app insights being in region disallowed by policy
```
[ ] Yes
[x] No
```
=> DTSPO-13832 - Add depends_on for app insights

infrastructure/main.tf
https://tools.hmcts.net/jira/browse/DTSPO-13832
Remove feature from provider to allow nested resource deletion
No longer needed now that draft store single servers are gone
```
[ ] Yes
[x] No
```
=> DTSPO-13832 - remove allow nested resource deletion

infrastructure/app-insights.tf, infrastructure/main.tf
https://tools.hmcts.net/jira/browse/DTSPO-14238
I've migrated the app insights instances with:
```bash
az monitor app-insights component update --app draft-store-service-appinsights-aat -g draft-store-service-aat --workspace "/subscriptions/1c4f0704-a29e-403d-b719-b90c34ef14c9/resourceGroups/oms-automation/providers/Microsoft.OperationalInsights/workspaces/hmcts-nonprod" --subscription DCD-CNP-DEV
ENV=perftest
az monitor app-insights component update --app draft-store-service-appinsights-$ENV -g draft-store-service-$ENV --workspace "/subscriptions/1c4f0704-a29e-403d-b719-b90c34ef14c9/resourceGroups/oms-automation/providers/Microsoft.OperationalInsights/workspaces/hmcts-nonprod" --subscription DCD-CNP-QA
ENV=ithc
az monitor app-insights component update --app …
```
=> DTSPO-14238 Migrate to workspace AI

build.gradle
https://tools.hmcts.net/jira/browse/DTSPO-12902
already using latest in https://github.com/hmcts/draft-store/blob/1b38699e1439ec7ff5a73933d65259f2dccba345/build.gradle#L240
```
[ ] Yes
[ ] No
```
=> Remove logging version - already defined and using latest version

.gitignore, charts/draft-store-service/Chart.yaml, charts/draft-store-service/values.preview.template.yaml
- [X ] commit messages are meaningful and follow good commit message guidelines
updated the draftstore to use the new ASO postgres server deployed through flux
```
[ ] Yes
[X ] No
```
=> configure to use new ASO postgres server

charts/draft-store-service/Chart.yaml, charts/draft-store-service/values.preview.template.yaml, charts/draft-store-service/values.yaml
- [X ] commit messages are meaningful and follow good commit message guidelines
https://tools.hmcts.net/jira/browse/DTSPO-15439
updating db name to include pr number in the db name
```
[ ] Yes
[X ] No
```
=> updated db name and postgresql version

charts/draft-store-service/Chart.yaml
DTSPO-15411
DTSPO-15411 - chart update for Workload Identity update
```
[ ] Yes
[ x] No
```
=> DTSPO-15411 - chart update for Workload Identity update

infrastructure/aat.tfvars, infrastructure/main.tf, infrastructure/sandbox.tfvars, infrastructure/variables.tf
Upgrade postgresql version 14->15 in place
```
[ ] Yes
[x ] No
```
=> Updated Sandbox DB version

infrastructure/demo.tfvars, infrastructure/ithc.tfvars, infrastructure/perftest.tfvars
Updated non prod database server to version 15
```
[ ] Yes
[x] No
```
=> Updated rest of the non prod DBs to 15

infrastructure/variables.tf
Upgrading prod database to version 15 after successful update of all the non prod environments.
=> CHG5015803 - Upgrade prod DB to version 15

build.gradle, charts/draft-store-service/Chart.yaml
=> Update to OCI
