hmcts/draft-store

src/functionalTest/java/uk/gov/hmcts/reform/draftstore/endpoint/v3/GetById.java
src/main/java/uk/gov/hmcts/reform/draftstore/data/DraftStoreDAO.java
src/main/java/uk/gov/hmcts/reform/draftstore/domain/Draft.java
src/main/java/uk/gov/hmcts/reform/draftstore/endpoint/v3/DraftController.java

One of many changes around API changes. 
Adding an endpoint for retrieving single draft by its ID.
```
[ ] Yes
[x] No
```

Read draft by ID

---

src/main/java/uk/gov/hmcts/reform/draftstore/data/DraftStoreDAO.java
src/main/java/uk/gov/hmcts/reform/draftstore/endpoint/v3/DraftController.java

Now supports both `/drafts` and `/drafts?type=xyz`
```
[ ] Yes
[x] No
```

Read drafts without filtering by type

---

README.md
src/main/java/uk/gov/hmcts/reform/draftstore/config/SwaggerConfiguration.java

Fix namespace for swagger to look for endpoints.  
Also remove api documentation from readme and provide link to swagger instead.
Please note that swagger is only enabled for `v2`, the new API is not finished yet.
```
[ ] Yes
[x] No
```

Fix swagger config

---

src/functionalTest/java/uk/gov/hmcts/reform/draftstore/endpoint/v3/GetAllTest.java
src/main/java/uk/gov/hmcts/reform/draftstore/domain/DraftList.java
src/main/java/uk/gov/hmcts/reform/draftstore/endpoint/v3/DraftController.java

So that it's in line with:
- https://hmcts.github.io/restful-api-standards/#167
- https://hmcts.github.io/restful-api-standards/#110
>In a response body, you must always return a JSON object (and not e.g. an array) as a top level data structure to support future extensibility. JSON objects support compatible extension by additional attributes. This allows you to easily extend your response and e.g. add pagination later, without breaking backwards compatibility.
```
[x] Yes
[ ] No
```

Wrap draft search results in a model

---

src/functionalTest/java/uk/gov/hmcts/reform/draftstore/endpoint/v3/DeleteTest.java
src/functionalTest/java/uk/gov/hmcts/reform/draftstore/endpoint/v3/GetByIdTest.java
src/functionalTest/java/uk/gov/hmcts/reform/draftstore/endpoint/v3/UpdateTest.java
src/main/java/uk/gov/hmcts/reform/draftstore/data/DraftStoreDAO.java
src/main/java/uk/gov/hmcts/reform/draftstore/domain/Draft.java
src/main/java/uk/gov/hmcts/reform/draftstore/endpoint/v3/DraftController.java

What: `id` field on returned model is now a string, not an int
Why: https://hmcts.github.io/restful-api-standards/#common-data-types
```
[x] Yes
[ ] No
```

Change draft id type to string

---

src/functionalTest/java/uk/gov/hmcts/reform/draftstore/data/DataAgent.java
src/functionalTest/java/uk/gov/hmcts/reform/draftstore/data/DraftStoreDAOTest.java
src/functionalTest/java/uk/gov/hmcts/reform/draftstore/endpoint/HandleUnknownExceptionTest.java
src/functionalTest/java/uk/gov/hmcts/reform/draftstore/endpoint/v3/CreateTest.java
src/functionalTest/java/uk/gov/hmcts/reform/draftstore/endpoint/v3/DeleteTest.java
src/functionalTest/java/uk/gov/hmcts/reform/draftstore/endpoint/v3/GetAllTest.java
src/functionalTest/java/uk/gov/hmcts/reform/draftstore/endpoint/v3/GetByIdTest.java
src/functionalTest/java/uk/gov/hmcts/reform/draftstore/endpoint/v3/UpdateTest.java
src/main/java/uk/gov/hmcts/reform/draftstore/data/DraftStoreDAO.java
src/main/java/uk/gov/hmcts/reform/draftstore/domain/Draft.java
src/main/java/uk/gov/hmcts/reform/draftstore/endpoint/v2/DraftStoreEndpoint.java
src/main/java/uk/gov/hmcts/reform/draftstore/endpoint/v3/DraftController.java
src/main/java/uk/gov/hmcts/reform/draftstore/service/UserIdentificationService.java
src/main/resources/db/migration/V4__add_service_column.sql

Add information to draft about service that created it.   
Old api uses hardcoded 'cmc' for backwards compatibility.  
New api requires `ServiceAuthorization` header for all operations.
```
[x] Yes (in v3, v2 remains the same)
[ ] No
```

Add information about service to draft

---

src/functionalTest/java/uk/gov/hmcts/reform/draftstore/endpoint/v3/CreateTest.java
src/functionalTest/java/uk/gov/hmcts/reform/draftstore/endpoint/v3/DeleteTest.java
src/functionalTest/java/uk/gov/hmcts/reform/draftstore/endpoint/v3/GetAllTest.java
src/functionalTest/java/uk/gov/hmcts/reform/draftstore/endpoint/v3/GetByIdTest.java
src/functionalTest/java/uk/gov/hmcts/reform/draftstore/endpoint/v3/UpdateTest.java
src/main/java/uk/gov/hmcts/reform/draftstore/config/DraftStoreConfig.java
src/main/java/uk/gov/hmcts/reform/draftstore/endpoint/EndpointExceptionHandler.java
src/main/java/uk/gov/hmcts/reform/draftstore/endpoint/v3/DraftController.java
src/main/java/uk/gov/hmcts/reform/draftstore/service/AuthService.java
src/main/java/uk/gov/hmcts/reform/draftstore/service/idam/IdamClient.java
src/main/java/uk/gov/hmcts/reform/draftstore/service/idam/IdamClientImpl.java
src/main/java/uk/gov/hmcts/reform/draftstore/service/idam/IdamClientStub.java
src/main/java/uk/gov/hmcts/reform/draftstore/service/idam/User.java
src/main/resources/application.yaml
src/test/java/uk/gov/hmcts/reform/draftstore/service/AuthServiceTest.java

Handle jwt in `Authorization` header (users only for now) in the new api by sending a request to Idam.
```
[x] Yes (v3 only)
[ ] No
```

use idam for user auth

---

docker-compose.yml

The image name it is published on has API on the end, I noticed when
building locally that my image tag wasn't getting overwritten.

Fix docker image name

---

src/functionalTest/java/uk/gov/hmcts/reform/draftstore/data/DraftStoreDAOTest.java
src/functionalTest/java/uk/gov/hmcts/reform/draftstore/data/OldDraftsCleanupTest.java
src/main/java/uk/gov/hmcts/reform/draftstore/config/DraftStoreConfig.java
src/main/java/uk/gov/hmcts/reform/draftstore/data/DraftStoreDAO.java
src/main/java/uk/gov/hmcts/reform/draftstore/endpoint/v3/DraftController.java
src/main/java/uk/gov/hmcts/reform/draftstore/exception/DraftStoreException.java
src/main/resources/db/migration/V7__use_jsonb_type.sql

Allows simple filtering by json document content using query params.  
For example:
```
/drafts?colour=red&size=large
```
Only string properties are supported.  
There was an endpoint previously that allowed filtering only by type (`/drafts?type=xxx`) which checked special 'type' column, it is no longer supported.    
The same functionality can be now achieved by adding 'type' field to actual json document.
```
[x] Yes (v3 only)
[ ] No
```

Filter drafts by json doc content

---

src/functionalTest/java/uk/gov/hmcts/reform/draftstore/data/DraftStoreDAOTest.java
src/functionalTest/java/uk/gov/hmcts/reform/draftstore/data/PaginationTest.java
src/functionalTest/java/uk/gov/hmcts/reform/draftstore/endpoint/v3/CreateTest.java
src/functionalTest/java/uk/gov/hmcts/reform/draftstore/endpoint/v3/UpdateTest.java
src/functionalTest/java/uk/gov/hmcts/reform/draftstore/endpoint/v3/helpers/SampleData.java
src/main/java/uk/gov/hmcts/reform/draftstore/data/DraftStoreDAO.java
src/main/java/uk/gov/hmcts/reform/draftstore/data/model/CreateDraft.java
src/main/java/uk/gov/hmcts/reform/draftstore/data/model/Draft.java
src/main/java/uk/gov/hmcts/reform/draftstore/data/model/UpdateDraft.java
src/main/java/uk/gov/hmcts/reform/draftstore/endpoint/EndpointExceptionHandler.java
src/main/java/uk/gov/hmcts/reform/draftstore/endpoint/v3/DraftController.java
src/main/java/uk/gov/hmcts/reform/draftstore/service/AuthService.java
src/main/java/uk/gov/hmcts/reform/draftstore/service/DraftService.java
src/main/java/uk/gov/hmcts/reform/draftstore/service/UserAndService.java
src/main/java/uk/gov/hmcts/reform/draftstore/service/crypto/CryptoService.java
src/main/java/uk/gov/hmcts/reform/draftstore/service/crypto/InvalidKeyException.java
src/main/java/uk/gov/hmcts/reform/draftstore/service/mappers/FromDbModelMapper.java
src/main/java/uk/gov/hmcts/reform/draftstore/service/mappers/ToDbModelMapper.java
src/main/resources/db/migration/V8__add_encrypted_doc_column.sql
src/test/java/uk/gov/hmcts/reform/draftstore/service/crypto/CryptoServiceTest.java
src/test/java/uk/gov/hmcts/reform/draftstore/service/draftservice/BaseTest.java
src/test/java/uk/gov/hmcts/reform/draftstore/service/mappers/FromDbModelMapperTest.java
src/test/java/uk/gov/hmcts/reform/draftstore/service/mappers/ToDbModelMapperTest.java

Makes it possible to draft-store clients to encrypt drafts.
As it is not mandatory during the transitions stage, database now has two columns
to store draft (in either plaintext or encrypted form) but only one column is
being populated:
For write operations, if header containg secret is set, document is encrypted
before storing in db using key derived from provided secret.
For read operations, if db row contains encrypted document, secret sent by the clients
will be used to decrypt the document.
Added a new set of models to be used by repository layer. Those models contain
data for both columns, repo just stores/retrieves the data.
The data transformation is handled by the service layer (added recently).

Optional draft encryption

---

.gitignore
build.gradle
src/gatling/resources/conf/application.conf
src/gatling/scala/uk/gov/hmcts/reform/draftstore/CreateMultipleDrafts.scala
src/gatling/scala/uk/gov/hmcts/reform/draftstore/actions/Create.scala
src/gatling/scala/uk/gov/hmcts/reform/draftstore/actions/ReadOne.scala

Added simple gatling test.  
Requires draft-store to use stub idam and s2s clients.
To do in next pull requests:
- add more tests
- handle idam
- handle s2s
To run locally:
```bash
./gradlew gatlingRun-uk.gov.hmcts.reform.draftstore.CreateMultipleDrafts
```
Results on my machine (response time in ms):
_ | Min | 50th pct | 75th pct | 95th pct | 99th pct | Max | Mean | Std De
-- | -- | -- | -- | -- | -- | -- | -- | --
create | 2 | 5 | 6 | 11 | 27 | 102 | 6 | 5
read | 1 | 2 | 3 | 5 | 9 | 143 | 3 | 4

Add simple gatling performance test

---

src/gatling/resources/conf/application.conf
src/gatling/scala/uk/gov/hmcts/reform/draftstore/CreateMultipleDrafts.scala
src/gatling/scala/uk/gov/hmcts/reform/draftstore/actions/Create.scala
src/gatling/scala/uk/gov/hmcts/reform/draftstore/actions/ReadOne.scala
src/gatling/scala/uk/gov/hmcts/reform/draftstore/actions/setup/LeaseServiceToken.scala

Retrieve s2s service token for each user in setup stage using `/testing-support` endpoint.
Property `auth.provider.service.testing-support.enabled` has to be set to `true` on s2s service.

Use s2s tokens in gatling tests

---

src/gatling/scala/uk/gov/hmcts/reform/draftstore/CreateMultipleDrafts.scala
src/gatling/scala/uk/gov/hmcts/reform/draftstore/actions/setup/LeaseServiceToken.scala

Previous implementation actually called method once resulting in using the same one random service name for all concurrent users.
```
[ ] Yes
[x] No
```

Use random s2s service names in gatling tests

---

.travis.yml
Jenkinsfile
README.md
build.gradle
src/functionalTest/java/uk/gov/hmcts/reform/draftstore/data/DraftStoreDAOTest.java
src/functionalTest/java/uk/gov/hmcts/reform/draftstore/data/OldDraftsCleanupTest.java
src/functionalTest/java/uk/gov/hmcts/reform/draftstore/data/PaginationTest.java
src/functionalTest/java/uk/gov/hmcts/reform/draftstore/endpoint/AbstractDraftStoreEndpointTest.java
src/functionalTest/java/uk/gov/hmcts/reform/draftstore/endpoint/HandleUnknownExceptionTest.java
src/functionalTest/resources/database.properties

None
Change introduces TestContainers to start database instance in docker environment prior to run functional tests. That should simplify development process by not requiring database to be 'up and running'  when functional tests are run.
TestContainers doc: https://www.testcontainers.org/usage/database_containers.html#benefits
```
[ ] Yes
[x] No
```

Use TestContainers to run functional tests

---

.travis.yml
publish-swagger-docs.sh

Bring back docker to travis (removed in https://github.com/hmcts/draft-store/pull/66) and increase sleep time

Fix publish swagger ci build step

---

src/functionalTest/java/uk/gov/hmcts/reform/draftstore/controllers/draftcontroller/CreateTest.java
src/functionalTest/java/uk/gov/hmcts/reform/draftstore/controllers/draftcontroller/UpdateTest.java
src/main/java/uk/gov/hmcts/reform/draftstore/controllers/DraftController.java

Add warning header to response if encryption is not used when creating/updating drafts

---

src/main/java/uk/gov/hmcts/reform/draftstore/data/DraftStoreDAO.java
src/main/java/uk/gov/hmcts/reform/draftstore/info/UnencryptedDraftsInfoContributor.java

Add info endpoint to check number of unencrypted drafts.
Sample response:
```
{
"app":{
"name":"HMCTS Draft Store"
},
"unecrypted_drafts":[
{
"service":"cmc",
"created":"2017-11-13T15:43:48Z",
"updated":"2017-11-13T15:43:48Z"
},
{
"service":"cmc",
"created":"2017-11-13T15:43:48Z",
"updated":"2017-11-13T15:43:48Z"
},
{
"service":"cmc",
"created":"2017-11-13T15:44:08Z",
"updated":"2017-11-13T15:44:08Z"
}
]
}
```
```
[ ] Yes
[x] No
```

Add info on unencrypted drafts

---

src/main/java/uk/gov/hmcts/reform/draftstore/controllers/DraftController.java

https://tools.hmcts.net/jira/browse/RPE-108
Added to handle versioning in the future. 
Current controllers handles both `application/json` and `application/vnd.uk.gov.hmcts.draft-store.v3+json`.
Any additional controllers will only handle specific version.
```
[ ] Yes
[x] No
```

Add api standard version content-type

---

src/main/java/uk/gov/hmcts/reform/draftstore/config/SwaggerConfiguration.java

Broken by recent namespace changes.
Does this PR introduce a breaking change?
```
[ ] Yes
[x] No
```

Fix swagger configuration

---

src/main/java/uk/gov/hmcts/reform/draftstore/service/idam/IdamClientStub.java
src/test/java/uk/gov/hmcts/reform/draftstore/service/idam/IdamClientStubTest.java

**Does this PR introduce a breaking change?**
```
[ ] Yes
[x] No
```

Handle short fake auth headers in idam client stub

---

README.md
src/functionalTest/java/uk/gov/hmcts/reform/draftstore/controllers/HandleUnknownExceptionTest.java
src/functionalTest/java/uk/gov/hmcts/reform/draftstore/controllers/draftcontroller/CreateTest.java
src/functionalTest/java/uk/gov/hmcts/reform/draftstore/controllers/draftcontroller/GetAllTest.java
src/functionalTest/java/uk/gov/hmcts/reform/draftstore/controllers/draftcontroller/GetByIdTest.java
src/functionalTest/java/uk/gov/hmcts/reform/draftstore/controllers/draftcontroller/UpdateTest.java
src/functionalTest/java/uk/gov/hmcts/reform/draftstore/controllers/helpers/SampleData.java
src/main/java/uk/gov/hmcts/reform/draftstore/controllers/DraftController.java
src/main/java/uk/gov/hmcts/reform/draftstore/service/mappers/ToDbModelMapper.java
src/main/java/uk/gov/hmcts/reform/draftstore/service/secrets/SecretsBuilder.java
src/test/java/uk/gov/hmcts/reform/draftstore/service/draftservice/UpdateTest.java
src/test/java/uk/gov/hmcts/reform/draftstore/service/mappers/SampleSecret.java
src/test/java/uk/gov/hmcts/reform/draftstore/service/mappers/ToDbModelMapperTest.java
src/test/java/uk/gov/hmcts/reform/draftstore/service/secrets/SecretsBuilderTest.java

Passing encryption header is now mandatory.
Please note, that this pull request **does not** remove the unencrypted document column from the database. This will have to be done separately in the future once all unencrypted drafts are gone/updated.
```
[x] Yes
[ ] No
```

Make encryption mandatory

---

infrastructure/main.tf
infrastructure/variables.tf

Use the same microservice name in terraform and Jenkinsfile. The pipeline makes assumptions that those are the same and will fail if they aren't. Currently, in Jenkinsfile the microservice is set to `service`.
```
[ ] Yes
[x] No
```

Use the same microservice name in terraform and Jenkinsfile

---

Jenkinsfile_parameterized

Use `withParameterizedPipeline` method in `Jenkinsfile_parameterized`. Current version (`withPipeline`) doesn't work with this set of arguments.
```
[ ] Yes
[x] No
```

Use withParameterizedPipeline method in Jenkinsfile_parameterized

---

build.gradle
src/smokeTest/java/uk/gov/hmcts/reform/draftstore/ApplicationSmokeTest.java
src/smokeTest/resources/application.properties

Add a basic smoke test (checking application's health), so that the build doesn't fail because of the lack of test report. Proper smoke tests are yet to come. This one is there to unblock the pipeline and be able to find other potential issues in further steps.
```
[ ] Yes
[x] No
```

Add a smoke test for application's health

---

build.gradle
src/functionalTest/java/uk/gov/hmcts/reform/draftstore/features/security/AuthenticatedRequestTest.java
src/functionalTest/resources/application.properties

Functional tests treat tested application as a black box: feeding data
and evaluating results.
Here is the first, basic test that expects HTTP status code 400 when
missing required headers.
https://tools.hmcts.net/jira/browse/RPE-342
```
[ ] Yes
[x] No
```

Add basic functional test

---

Jenkinsfile

Fix docker image creation in tactical Jenkins. The bootRepackage task breaks the step and doesn't seem to be needed anymore.
```
[ ] Yes
[x] No
```

Fix docker image creation in tactical Jenkins

---

build.gradle

Upgrade dependencycheck plugin to the latest version. This is required, as currently used version doesn't have dependencyCheckAnalyze task, which is executed by Jenkins.
```
[ ] Yes
[x] No
```

Upgrade dependencycheck plugin to the latest version

---

src/smokeTest/java/uk/gov/hmcts/reform/draftstore/SmokeTestSuite.java

Bug fix: return Idam auth token after user registration. Previously, it was authorisation code (bug was introduced during code refactoring).
```
[ ] Yes
[x] No
```

Return Idam auth token after user registration

---

src/smokeTest/java/uk/gov/hmcts/reform/draftstore/SmokeTestSuite.java
src/smokeTest/java/uk/gov/hmcts/reform/draftstore/client/IdamClient.java

If there's an Idam authentication failure on user login, smoke tests make an attempt to create that user and try to log them in again. However, if the user already exists but is locked, creation won't change their state and the tests will end up in a forever failing state. That's why before creating the user we should make sure the user doesn't exist.
```
[ ] Yes
[x] No
```

Delete smoke test user before creation attempt

---

build.gradle
dependency-check-suppressions.xml

[Remediate suppressed dependencies across micro services](https://tools.hmcts.net/jira/browse/RPE-405)
- spring boot downgraded to `1.5.10` because `1.5.12` pulled in `tomcat-annotations-api-8.5.29` which has a lot of vulnerabilities compared to enlisted `8.5.27` version (see suppression file)
- missed dependency update of `jackson` lib in previous (#139) pr. #136 upgraded the `java-logging` library which has latest stable `jackson` library implemented
```
[ ] Yes
[x] No
```

Fix dependencies

---

infrastructure/output.tf
infrastructure/prod.tfvars
infrastructure/variables.tf
src/smokeTest/java/uk/gov/hmcts/reform/draftstore/SmokeTestSuite.java
src/smokeTest/resources/application.properties

Let smoke tests use Idam testing support only in environments where it's available (i.e. not in production)
```
[ ] Yes
[x] No
```

Let smoke tests use Idam testing support only where it's available

---

infrastructure/aat.tfvars
infrastructure/demo.tfvars
infrastructure/output.tf
infrastructure/prod.tfvars
infrastructure/variables.tf

Make redirect-uris for Idam (tests only) environment-specific.
In order to log a test user into Idam, smoke/functional tests need to provide `redirect-uri` paramter. In our case that URI doesn't matter, as long as it's whitelisted. Each environment has its own whitelist, which has to be reflected in our configuration.
```
[ ] Yes
[x] No
```

Make redirect-uris for Idam (tests only) environment-specific

---

infrastructure/test_config.tf

This password is set only in those environments where IdAM's testing support is on. It still has to be set manually everywhere else.
```
[ ] Yes
[x] No
```

Set IdAM test user's password in terraform

---

src/integrationTest/java/uk/gov/hmcts/reform/draftstore/controllers/helpers/SampleData.java
src/integrationTest/java/uk/gov/hmcts/reform/draftstore/data/OldDraftsCleanupTest.java
src/main/java/uk/gov/hmcts/reform/draftstore/data/DraftStoreDao.java

uses 'default max stale days' from config for such drafts

Delete stale drafts with null max stale days field

---

Jenkinsfile_parameterized

Currently builds on sandbox fail, as jenkins tries to run migration but does not have access to tactical env db.

Disable migrations on sandbox

---

infrastructure/variables.tf

Previously used `https://i-am-not-used/receiver` is no longer whitelisted
(it was removed in https://github.com/hmcts/idam-ansible/pull/38/files)

Update idam redirect url for sandbox smoke tests

---

src/integrationTest/java/uk/gov/hmcts/reform/draftstore/controllers/draftcontroller/GetByIdTest.java
src/main/java/uk/gov/hmcts/reform/draftstore/controllers/EndpointExceptionHandler.java
src/main/java/uk/gov/hmcts/reform/draftstore/domain/ErrorCode.java
src/main/java/uk/gov/hmcts/reform/draftstore/service/idam/IdamClientImpl.java
src/main/java/uk/gov/hmcts/reform/draftstore/service/idam/InvalidIdamTokenException.java
src/main/java/uk/gov/hmcts/reform/draftstore/service/s2s/InvalidServiceTokenException.java
src/main/java/uk/gov/hmcts/reform/draftstore/service/s2s/S2sClientImpl.java

`HttpClientErrorException` was quite vague in logs.
Wrapped in custom runtime exceptions so that it's clear we were validating Idam/s2s token.

Clearer exception for idam token validation errors

---

infrastructure/main.tf

Currently not used by the application.
Connection string for the app will be updated in next PR
(and merged after data from tactical db is migrated)

[SKIP-PREVIEW] Create db on cnp

---

src/integrationTest/java/uk/gov/hmcts/reform/draftstore/data/DataAgent.java
src/integrationTest/java/uk/gov/hmcts/reform/draftstore/data/DraftStoreDaoTest.java

depending on the tests order, some would fail, because this:
```
@Before
public void cleanDb() {
dataAgent.deleteDocuments(USER_ID);
dataAgent.deleteDocuments(ANOTHER_USER_ID);
}
```
did not remove all the drafts (see changes below)

[SKIP-PREVIEW] Fix db cleanup in tests

---

infrastructure/saat.tfvars

strategic IDAM doesn't have this endpoint anyway

Disable idam testing support on saat env

---

infrastructure/prod.tfvars

Needed for SIDAM go-live, CMC have been using the version without a port for weeks,
App services don't support a port in the url, on go-live it'll be a DNS switch but the port must not be there

Drop port in IDAM url

---

Jenkinsfile_nightly

Add support for nightly OWASP dependency checks with slack notifications.
Successful build here https://build.platform.hmcts.net/job/HMCTS_Nightly/job/draft-store/job/nightly-pipeline/
```
[ ] Yes
[ x] No
```

Add basic nightly pipeline

---

infrastructure/prod.tfvars

-
Idam is migrating to the platform domain, so that after the DNS switch for SIDAM it will be on the new domain, a request should have came through for us to update it but draft-store must've been missed
https://github.com/hmcts/cmc-citizen-frontend/pull/875/files
```
[ ] Yes
[ ] No
```

Update to new idam prod url

---

infrastructure/main.tf
infrastructure/output.tf
infrastructure/test_config.tf

https://tools.hmcts.net/jira/browse/RPE-544
Retrieve test secrets from Azure Key Vault and not Hashicorp Vault
```
[ ] Yes
[x] No
```

[PREVIEW] Retrieve test secrets from Azure Key Vault and not Hashicorp Vault

---

infrastructure/sandbox.tfvars

Point sandbox to tactical Idam. Strategic Idam is not deployed there, preventing draft store from being deployed (which is needed for migration of secrets)
```
[ ] Yes
[x] No
```

Point sandbox to tactical Idam

---

infrastructure/test_config.tf

https://tools.hmcts.net/jira/browse/RPE-544
Retrieve test s2s key directly from s2s's vault. Before this change it was kept independently in draft-store's vault.
```
[ ] Yes
[x] No
```

[PREVIEW] Retrieve test s2s key directly from s2s's vault

---

infrastructure/main.tf

Add a prefix to DB server name so that it's globally unique. Currently, there's a name conflict in demo.
```
[ ] Yes
[x] No
```

[PREVIEW] Add a prefix to DB server name

---

infrastructure/main.tf

https://tools.hmcts.net/jira/browse/RPE-544
Remove (Hashicorp) vault provider config from infrastructure code. We're not using Hashicorp vault anymore.
```
[ ] Yes
[x] No
```

[PREVIEW] Remove (Hashicorp) vault provider config from infrastructure code

---

build.gradle
src/main/java/uk/gov/hmcts/reform/draftstore/controllers/DraftController.java

Use javax annotation instead of hibernate
```
/**
* The annotated element size must be between the specified boundaries (included).
* <p/>
* Supported types are:
* <ul>
*     <li>{@code CharSequence} (length of character sequence is evaluated)</li>
*     <li>{@code Collection} (collection size is evaluated)</li>
*     <li>{@code Map} (map size is evaluated)</li>
*     <li>Array (array length is evaluated)</li>
* </ul>
* <p/>
* {@code null} elements are considered valid.
*
* @author Emmanuel Bernard
*/
@Target({ METHOD, FIELD, ANNOTATION_TYPE, CONSTRUCTOR, PARAMETER })
@Retention(RUNTIME)
@Documented
@Constraint(validatedBy = { })
public @interface Size {
```
`String` implements `CharSequence`.

Simplify secret length validation

---

dependency-check-suppressions.xml

Suppress a dependency warning, as the dependency is used in tests only. The newest version of `org.testcontainers.postgresql`, which contains the dependency, is used.
```
[ ] Yes
[x] No
```

Suppress a dependency warning

---

docker-compose.yml

none
Without this change the docker-compose file didn't work, complained about it being an array and it didn't want that... 
```
[ ] Yes
[ ] No
```

Fix docker-compose config

---

charts/draft-store-service/requirements.yaml

This change will prevent pod from running container processes as root, please refer to the documentation for more details:
https://tools.hmcts.net/confluence/display/CNP/Pod+Security#PodSecurity-SecurityContext
IMPORTANT: Please ensure to update java helm chart version as we might be deleting/deprecating older helm charts from Azure Container Registry which will make the AKS preview deployments fail
```
[ ] Yes
[ ] No
```

CNP-1155-Java-chart-version - prevent pod from running container process as root

---

src/integrationTest/java/uk/gov/hmcts/reform/draftstore/data/DraftStoreDaoTest.java
src/main/java/uk/gov/hmcts/reform/draftstore/controllers/ReportController.java
src/main/java/uk/gov/hmcts/reform/draftstore/data/DraftStoreDao.java
src/main/java/uk/gov/hmcts/reform/draftstore/data/model/DocumentTypeCount.java
src/main/java/uk/gov/hmcts/reform/draftstore/service/AuthService.java
src/main/java/uk/gov/hmcts/reform/draftstore/service/DraftService.java
src/test/java/uk/gov/hmcts/reform/draftstore/service/draftservice/UserReportTest.java

https://tools.hmcts.net/jira/browse/ROC-5323
Add reports endpoint to query the draft document type counts of a user.
Caller must be signed in to IDaM but there are no further role restrictions in place.
This is to facilitate Live Support work.
```
[ ] Yes
[x] No
```

ROC-5323 user's document type counts report endpoint

---

build.gradle
config/owasp/suppressions.xml

disable .Net scanning to resolve repetitive daily build failures
None
Turn off .Net scanning during dependency Check
```
[ ] Yes
[x ] No
```

disabe .Net scanning

---

infrastructure/main.tf

fixed in https://github.com/hmcts/cnp-module-postgres/pull/59
Reverts hmcts/draft-store#789

DTSPO-264 Set name for postgres DB

---

build.gradle
charts/draft-store-service/Chart.yaml
charts/draft-store-service/values.preview.template.yaml
charts/draft-store-service/values.yaml
src/main/resources/application.yaml
src/main/resources/bootstrap.yaml

- Use spring boot configtree instead of properties-volume-springboot-starter
- Change to use `disableKeyvaults`in preview as `SPRING_CLOUD_PROPERTIESVOLUME_ENABLED` won't work anymore.
- Using alias in secretproviderclass to rename secrets to env vars/spring properties.
- Also upgrades other dependencies as there were bunch of vulnerabilities.
```
[ ] Yes
[x] No
```

Spring boot 2.4 upgrade with configtree

---

src/main/resources/db/migration/V9__add_user_id_to_service_index.sql

CMC said they were moving away from draft store partly because of performance.
I checked prod and the only performance issue appears to be this missing index =/

Add index on user_id and service

---

Jenkinsfile_CNP
infrastructure/main.tf

Remove PostgreSQL v11 instance for draft store. No longer required as PlatOps will be migrating v10 to Flexible SErver v14
```
[ ] Yes
[x ] No
```

Remove PostgreSQL v11 instance for draft store

---

infrastructure/aat.tfvars
infrastructure/sandbox.tfvars
infrastructure/test_config.tf

https://tools.hmcts.net/jira/browse/DTSPO-17912
Change create mode to default from update
This is causing a 404 error when deploying but the update mode should only be used when updating the postgres version as well
```
[ ] Yes
[x] No
```

DTSPO-17910 - Change create_mode
